const data = {
    products: [
        {
            name: 'Ceviche de pescado ',
            slug: 'ceviche-pescado',
            category: 'mariscos',
            image: '/images/ceviche-pescado.jpg',
            price: 20,
            countInStock: 10,
            dealership: 'Cafeteria O1',
            rating: 2.5,
            numReviews: 5,
            description: 'Plato de mariscos encebollados y cocidos en limón, acompañados de camote, maíz y cebolla morada.'
        },
        {
            name: 'Papa a la huancaína',
            slug: 'papa-huancaina',
            category: 'vegetariano',
            image: '/images/papa-huancaina.jpg',
            price: 8,
            countInStock: 5,
            dealership: 'Cafeteria F2',
            rating: 4.0,
            numReviews: 3,
            description: 'Papas cocidas y cortadas en rodajas, bañadas en una salsa de ají amarillo, leche y queso.'
        },
        {
            name: 'Anticuchos de corazón',
            slug: 'anticucho-corazon',
            category: 'carnes',
            image: '/images/anticucho-corazon.jpg',
            price: 18,
            countInStock: 20,
            dealership: 'Cafeteria O1',
            rating: 5.0,
            numReviews: 10,
            description: 'Brochetas de corazón de res marinado en ajo, comino y ají panca, asadas en parrilla.'
        },
        {
            name: 'Tallarín saltado',
            slug: 'tallarin-saltado',
            category: 'carnes',
            image: '/images/tallarin-saltado.jpg',
            price: 22,
            countInStock: 10,
            dealership: 'Cafeteria O1',
            rating: 4.0,
            numReviews: 2,
            description: 'Tallarines salteados con carne, cebolla, tomate y ají amarillo, acompañados con papas fritas.'
        },
        {
            name: 'Lomo saltado',
            slug: 'lomo-saltado',
            category: 'carnes',
            image: '/images/lomo-saltado.jpg',
            price: 16,
            countInStock: 4,
            dealership: 'Cafeteria F2',
            rating: 4.5,
            numReviews: 3,
            description: 'Carne de res cortada en tiras y salteada con cebolla, tomate, cilantro y papas fritas.'
        },
        {
            name: 'Rocoto relleno',
            slug: 'rocoto-relleno',
            category: 'carnes',
            image: '/images/rocoto-relleno.jpg',
            price: 25,
            countInStock: 10,
            dealership: 'Cafeteria F2',
            rating: 4.5,
            numReviews: 4,
            description: 'Rocoto relleno con carne picada, pasas, aceitunas y papas, gratinado con queso.'
        },
        {
            name: 'Pollo a la brasa',
            slug: 'pollo-brasa',
            category: 'aves',
            image: '/images/pollo-brasa.jpg',
            price: 15,
            countInStock: 20,
            dealership: 'Cafeteria O1',
            rating: 1.0,
            numReviews: 1,
            description: 'Pollo marinado en una mezcla de especias y cocido en parrilla.'
        },
        {
            name: 'Adobo de cerdo',
            slug: 'adobo-cerdo',
            category: 'carnes',
            image: '/images/adobo-cerdo.jpg',
            price: 23,
            countInStock: 8,
            dealership: 'Cafeteria F2',
            rating: 4.5,
            numReviews: 8,
            description: 'Carne de cerdo marinada en una salsa de ají panca, ajo, vinagre y comino, acompañada de papas cocidas y choclo.'
        },
        {
            //_id: '9',
            name: "Tiradito de pescado",
            slug: "tiradito-pescado",
            category: "pescado",
            image: "/images/tiradito-pescado.jpg",
            price: 18,
            countInStock: 8,
            dealership: "Cafeteria O1",
            rating: 3.0,
            numReviews: 3,
            description:
              "Finas láminas de pescado marinadas en limón y ají amarillo, servidas con salsa de rocoto y canchita.",
            WeekDay: [0, 3, 4],
          },
          {
            //_id: '10',
            name: "Ají de gallina",
            slug: "aji-gallina",
            category: "aves",
            image: "/images/aji-gallina.jpg",
            price: 15,
            countInStock: 5,
            dealership: "Cafeteria F2",
            rating: 4.0,
            numReviews: 8,
            description:
              "Pollo deshilachado en una salsa cremosa de ají amarillo, acompañado de arroz y papas.",
            WeekDay: [1, 4, 6],
          },
          {
            //_id: '11',
            name: "Seco de cordero",
            slug: "seco-cordero",
            category: "carnes",
            image: "/images/seco-cordero.jpg",
            price: 26,
            countInStock: 3,
            dealership: "Cafeteria O1",
            rating: 4.5,
            numReviews: 6,
            description:
              "Estofado de cordero con hierbas y especias, acompañado de frejoles, arroz y yuca.",
            WeekDay: [2, 3, 5],
          },
          {
            //_id: '11',
            name: "Causa limeña",
            slug: "causa-limena",
            category: "aperitivos",
            image: "/images/causa-limena.jpg",
            price: 12,
            countInStock: 8,
            dealership: "Cafeteria F2",
            rating: 4.5,
            numReviews: 10,
            description:
              "Pastel de papas amarillas sazonadas con ají amarillo y relleno de pollo, atún o mariscos.",
            WeekDay: [0, 1, 4],
          },
          {
            //_id: '12',
            name: "Chupe de camarones",
            slug: "chupe-camarones",
            category: "mariscos",
            image: "/images/chupe-camarones.jpg",
            price: 24,
            countInStock: 6,
            dealership: "Cafeteria O1",
            rating: 4.0,
            numReviews: 7,
            description:
              "Sopa cremosa de camarones con papas, maíz, queso y un toque de ají amarillo.",
            WeekDay: [1, 3, 6],
          },
          {
            //_id: '13',
            name: "Arroz con mariscos",
            slug: "arroz-mariscos",
            category: "mariscos",
            image: "/images/arroz-mariscos.jpg",
            price: 28,
            countInStock: 5,
            dealership: "Cafeteria F2",
            rating: 4.5,
            numReviews: 9,
            description:
              "Arroz preparado con una variedad de mariscos como camarones, calamares y mejillones, sazonado con especias y ají amarillo.",
            WeekDay: [2, 4, 5],
          }
    ]
};
export default data;